version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/typescript"
    schedule:
      interval: "weekly"
    groups:
      npm-minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "uv"
    directory: "/python"
    schedule:
      interval: "weekly"
    groups:
      uv-minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "gomod"
    directories:
      - "/go/arcadedb"
      - "/go/arcadedbgrpc"
      - "/go/e2e"
      - "/go/tools"
    schedule:
      interval: "weekly"
    groups:
      gomod-minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
