# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from arcadedb_driver_grpc._generated import arcadedb_server_pb2 as arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in arcadedb_driver_grpc/_generated/arcadedb_server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArcadeDbServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamQuery = channel.unary_stream(
                '/com.arcadedb.grpc.ArcadeDbService/StreamQuery',
                request_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.StreamQueryRequest.SerializeToString,
                response_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.QueryResult.FromString,
                _registered_method=True)
        self.ExecuteCommand = channel.unary_unary(
                '/com.arcadedb.grpc.ArcadeDbService/ExecuteCommand',
                request_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.ExecuteCommandRequest.SerializeToString,
                response_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.ExecuteCommandResponse.FromString,
                _registered_method=True)
        self.ExecuteQuery = channel.unary_unary(
                '/com.arcadedb.grpc.ArcadeDbService/ExecuteQuery',
                request_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.ExecuteQueryRequest.SerializeToString,
                response_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.ExecuteQueryResponse.FromString,
                _registered_method=True)
        self.CreateRecord = channel.unary_unary(
                '/com.arcadedb.grpc.ArcadeDbService/CreateRecord',
                request_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.CreateRecordRequest.SerializeToString,
                response_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.CreateRecordResponse.FromString,
                _registered_method=True)
        self.UpdateRecord = channel.unary_unary(
                '/com.arcadedb.grpc.ArcadeDbService/UpdateRecord',
                request_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.UpdateRecordRequest.SerializeToString,
                response_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.UpdateRecordResponse.FromString,
                _registered_method=True)
        self.LookupByRid = channel.unary_unary(
                '/com.arcadedb.grpc.ArcadeDbService/LookupByRid',
                request_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.LookupByRidRequest.SerializeToString,
                response_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.LookupByRidResponse.FromString,
                _registered_method=True)
        self.DeleteRecord = channel.unary_unary(
                '/com.arcadedb.grpc.ArcadeDbService/DeleteRecord',
                request_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.DeleteRecordRequest.SerializeToString,
                response_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.DeleteRecordResponse.FromString,
                _registered_method=True)
        self.BulkInsert = channel.unary_unary(
                '/com.arcadedb.grpc.ArcadeDbService/BulkInsert',
                request_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.BulkInsertRequest.SerializeToString,
                response_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.InsertSummary.FromString,
                _registered_method=True)
        self.InsertStream = channel.stream_unary(
                '/com.arcadedb.grpc.ArcadeDbService/InsertStream',
                request_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.InsertChunk.SerializeToString,
                response_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.InsertSummary.FromString,
                _registered_method=True)
        self.InsertBidirectional = channel.stream_stream(
                '/com.arcadedb.grpc.ArcadeDbService/InsertBidirectional',
                request_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.InsertRequest.SerializeToString,
                response_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.InsertResponse.FromString,
                _registered_method=True)
        self.BeginTransaction = channel.unary_unary(
                '/com.arcadedb.grpc.ArcadeDbService/BeginTransaction',
                request_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.BeginTransactionRequest.SerializeToString,
                response_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.BeginTransactionResponse.FromString,
                _registered_method=True)
        self.CommitTransaction = channel.unary_unary(
                '/com.arcadedb.grpc.ArcadeDbService/CommitTransaction',
                request_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.CommitTransactionRequest.SerializeToString,
                response_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.CommitTransactionResponse.FromString,
                _registered_method=True)
        self.RollbackTransaction = channel.unary_unary(
                '/com.arcadedb.grpc.ArcadeDbService/RollbackTransaction',
                request_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.RollbackTransactionRequest.SerializeToString,
                response_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.RollbackTransactionResponse.FromString,
                _registered_method=True)
        self.GraphBatchLoad = channel.stream_unary(
                '/com.arcadedb.grpc.ArcadeDbService/GraphBatchLoad',
                request_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.GraphBatchChunk.SerializeToString,
                response_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.GraphBatchResult.FromString,
                _registered_method=True)


class ArcadeDbServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StreamQuery(self, request, context):
        """Streaming queries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """Execute arbitrary command (INSERT/UPDATE/DDL/etc.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRecord(self, request, context):
        """Single-record helpers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LookupByRid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkInsert(self, request, context):
        """Insert APIs (unary, client-streaming, and bidi)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertBidirectional(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginTransaction(self, request, context):
        """Transaction operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollbackTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GraphBatchLoad(self, request_iterator, context):
        """Graph batch load (client-streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArcadeDbServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamQuery': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamQuery,
                    request_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.StreamQueryRequest.FromString,
                    response_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.QueryResult.SerializeToString,
            ),
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.ExecuteCommandRequest.FromString,
                    response_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.ExecuteCommandResponse.SerializeToString,
            ),
            'ExecuteQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteQuery,
                    request_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.ExecuteQueryRequest.FromString,
                    response_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.ExecuteQueryResponse.SerializeToString,
            ),
            'CreateRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRecord,
                    request_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.CreateRecordRequest.FromString,
                    response_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.CreateRecordResponse.SerializeToString,
            ),
            'UpdateRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRecord,
                    request_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.UpdateRecordRequest.FromString,
                    response_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.UpdateRecordResponse.SerializeToString,
            ),
            'LookupByRid': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupByRid,
                    request_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.LookupByRidRequest.FromString,
                    response_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.LookupByRidResponse.SerializeToString,
            ),
            'DeleteRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRecord,
                    request_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.DeleteRecordRequest.FromString,
                    response_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.DeleteRecordResponse.SerializeToString,
            ),
            'BulkInsert': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkInsert,
                    request_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.BulkInsertRequest.FromString,
                    response_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.InsertSummary.SerializeToString,
            ),
            'InsertStream': grpc.stream_unary_rpc_method_handler(
                    servicer.InsertStream,
                    request_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.InsertChunk.FromString,
                    response_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.InsertSummary.SerializeToString,
            ),
            'InsertBidirectional': grpc.stream_stream_rpc_method_handler(
                    servicer.InsertBidirectional,
                    request_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.InsertRequest.FromString,
                    response_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.InsertResponse.SerializeToString,
            ),
            'BeginTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginTransaction,
                    request_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.BeginTransactionRequest.FromString,
                    response_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.BeginTransactionResponse.SerializeToString,
            ),
            'CommitTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitTransaction,
                    request_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.CommitTransactionRequest.FromString,
                    response_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.CommitTransactionResponse.SerializeToString,
            ),
            'RollbackTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackTransaction,
                    request_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.RollbackTransactionRequest.FromString,
                    response_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.RollbackTransactionResponse.SerializeToString,
            ),
            'GraphBatchLoad': grpc.stream_unary_rpc_method_handler(
                    servicer.GraphBatchLoad,
                    request_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.GraphBatchChunk.FromString,
                    response_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.GraphBatchResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.arcadedb.grpc.ArcadeDbService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.arcadedb.grpc.ArcadeDbService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArcadeDbService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.arcadedb.grpc.ArcadeDbService/StreamQuery',
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.StreamQueryRequest.SerializeToString,
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.QueryResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.arcadedb.grpc.ArcadeDbService/ExecuteCommand',
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.ExecuteCommandRequest.SerializeToString,
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.ExecuteCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.arcadedb.grpc.ArcadeDbService/ExecuteQuery',
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.ExecuteQueryRequest.SerializeToString,
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.ExecuteQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.arcadedb.grpc.ArcadeDbService/CreateRecord',
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.CreateRecordRequest.SerializeToString,
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.CreateRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.arcadedb.grpc.ArcadeDbService/UpdateRecord',
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.UpdateRecordRequest.SerializeToString,
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.UpdateRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LookupByRid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.arcadedb.grpc.ArcadeDbService/LookupByRid',
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.LookupByRidRequest.SerializeToString,
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.LookupByRidResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.arcadedb.grpc.ArcadeDbService/DeleteRecord',
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.DeleteRecordRequest.SerializeToString,
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.DeleteRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BulkInsert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.arcadedb.grpc.ArcadeDbService/BulkInsert',
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.BulkInsertRequest.SerializeToString,
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.InsertSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/com.arcadedb.grpc.ArcadeDbService/InsertStream',
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.InsertChunk.SerializeToString,
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.InsertSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertBidirectional(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/com.arcadedb.grpc.ArcadeDbService/InsertBidirectional',
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.InsertRequest.SerializeToString,
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.InsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BeginTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.arcadedb.grpc.ArcadeDbService/BeginTransaction',
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.BeginTransactionRequest.SerializeToString,
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.BeginTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.arcadedb.grpc.ArcadeDbService/CommitTransaction',
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.CommitTransactionRequest.SerializeToString,
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.CommitTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollbackTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.arcadedb.grpc.ArcadeDbService/RollbackTransaction',
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.RollbackTransactionRequest.SerializeToString,
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.RollbackTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GraphBatchLoad(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/com.arcadedb.grpc.ArcadeDbService/GraphBatchLoad',
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.GraphBatchChunk.SerializeToString,
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.GraphBatchResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ArcadeDbAdminServiceStub:
    """-----------------------------------------------------------------------------
    Admin service
    -----------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/com.arcadedb.grpc.ArcadeDbAdminService/Ping',
                request_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.PingRequest.SerializeToString,
                response_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.PingResponse.FromString,
                _registered_method=True)
        self.GetServerInfo = channel.unary_unary(
                '/com.arcadedb.grpc.ArcadeDbAdminService/GetServerInfo',
                request_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.GetServerInfoRequest.SerializeToString,
                response_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.GetServerInfoResponse.FromString,
                _registered_method=True)
        self.ListDatabases = channel.unary_unary(
                '/com.arcadedb.grpc.ArcadeDbAdminService/ListDatabases',
                request_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.ListDatabasesRequest.SerializeToString,
                response_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.ListDatabasesResponse.FromString,
                _registered_method=True)
        self.ExistsDatabase = channel.unary_unary(
                '/com.arcadedb.grpc.ArcadeDbAdminService/ExistsDatabase',
                request_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.ExistsDatabaseRequest.SerializeToString,
                response_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.ExistsDatabaseResponse.FromString,
                _registered_method=True)
        self.CreateDatabase = channel.unary_unary(
                '/com.arcadedb.grpc.ArcadeDbAdminService/CreateDatabase',
                request_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.CreateDatabaseRequest.SerializeToString,
                response_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.CreateDatabaseResponse.FromString,
                _registered_method=True)
        self.DropDatabase = channel.unary_unary(
                '/com.arcadedb.grpc.ArcadeDbAdminService/DropDatabase',
                request_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.DropDatabaseRequest.SerializeToString,
                response_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.DropDatabaseResponse.FromString,
                _registered_method=True)
        self.GetDatabaseInfo = channel.unary_unary(
                '/com.arcadedb.grpc.ArcadeDbAdminService/GetDatabaseInfo',
                request_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.GetDatabaseInfoRequest.SerializeToString,
                response_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.GetDatabaseInfoResponse.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/com.arcadedb.grpc.ArcadeDbAdminService/CreateUser',
                request_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.CreateUserResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/com.arcadedb.grpc.ArcadeDbAdminService/DeleteUser',
                request_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.DeleteUserResponse.FromString,
                _registered_method=True)


class ArcadeDbAdminServiceServicer:
    """-----------------------------------------------------------------------------
    Admin service
    -----------------------------------------------------------------------------

    """

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDatabases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExistsDatabase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDatabase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropDatabase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDatabaseInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArcadeDbAdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.PingRequest.FromString,
                    response_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.PingResponse.SerializeToString,
            ),
            'GetServerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerInfo,
                    request_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.GetServerInfoRequest.FromString,
                    response_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.GetServerInfoResponse.SerializeToString,
            ),
            'ListDatabases': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDatabases,
                    request_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.ListDatabasesRequest.FromString,
                    response_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.ListDatabasesResponse.SerializeToString,
            ),
            'ExistsDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.ExistsDatabase,
                    request_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.ExistsDatabaseRequest.FromString,
                    response_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.ExistsDatabaseResponse.SerializeToString,
            ),
            'CreateDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDatabase,
                    request_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.CreateDatabaseRequest.FromString,
                    response_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.CreateDatabaseResponse.SerializeToString,
            ),
            'DropDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.DropDatabase,
                    request_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.DropDatabaseRequest.FromString,
                    response_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.DropDatabaseResponse.SerializeToString,
            ),
            'GetDatabaseInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDatabaseInfo,
                    request_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.GetDatabaseInfoRequest.FromString,
                    response_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.GetDatabaseInfoResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.CreateUserRequest.FromString,
                    response_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.CreateUserResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.DeleteUserRequest.FromString,
                    response_serializer=arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.DeleteUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.arcadedb.grpc.ArcadeDbAdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.arcadedb.grpc.ArcadeDbAdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArcadeDbAdminService:
    """-----------------------------------------------------------------------------
    Admin service
    -----------------------------------------------------------------------------

    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.arcadedb.grpc.ArcadeDbAdminService/Ping',
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.PingRequest.SerializeToString,
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.arcadedb.grpc.ArcadeDbAdminService/GetServerInfo',
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.GetServerInfoRequest.SerializeToString,
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.GetServerInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDatabases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.arcadedb.grpc.ArcadeDbAdminService/ListDatabases',
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.ListDatabasesRequest.SerializeToString,
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.ListDatabasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExistsDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.arcadedb.grpc.ArcadeDbAdminService/ExistsDatabase',
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.ExistsDatabaseRequest.SerializeToString,
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.ExistsDatabaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.arcadedb.grpc.ArcadeDbAdminService/CreateDatabase',
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.CreateDatabaseRequest.SerializeToString,
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.CreateDatabaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.arcadedb.grpc.ArcadeDbAdminService/DropDatabase',
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.DropDatabaseRequest.SerializeToString,
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.DropDatabaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDatabaseInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.arcadedb.grpc.ArcadeDbAdminService/GetDatabaseInfo',
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.GetDatabaseInfoRequest.SerializeToString,
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.GetDatabaseInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.arcadedb.grpc.ArcadeDbAdminService/CreateUser',
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.CreateUserRequest.SerializeToString,
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.CreateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.arcadedb.grpc.ArcadeDbAdminService/DeleteUser',
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.DeleteUserRequest.SerializeToString,
            arcadedb__driver__grpc_dot___generated_dot_arcadedb__server__pb2.DeleteUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
