"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Copyright © 2021-present Arcade Data Ltd (info@arcadedata.com)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from arcadedb_driver_grpc._generated import arcadedb_server_pb2 as _arcadedb_server_pb2
from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ArcadeDbServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ArcadeDbServiceAsyncStub: ...
    StreamQuery: _grpc.UnaryStreamMultiCallable[_arcadedb_server_pb2.StreamQueryRequest, _arcadedb_server_pb2.QueryResult]
    """Streaming queries"""
    ExecuteCommand: _grpc.UnaryUnaryMultiCallable[_arcadedb_server_pb2.ExecuteCommandRequest, _arcadedb_server_pb2.ExecuteCommandResponse]
    """Execute arbitrary command (INSERT/UPDATE/DDL/etc.)"""
    ExecuteQuery: _grpc.UnaryUnaryMultiCallable[_arcadedb_server_pb2.ExecuteQueryRequest, _arcadedb_server_pb2.ExecuteQueryResponse]
    CreateRecord: _grpc.UnaryUnaryMultiCallable[_arcadedb_server_pb2.CreateRecordRequest, _arcadedb_server_pb2.CreateRecordResponse]
    """Single-record helpers"""
    UpdateRecord: _grpc.UnaryUnaryMultiCallable[_arcadedb_server_pb2.UpdateRecordRequest, _arcadedb_server_pb2.UpdateRecordResponse]
    LookupByRid: _grpc.UnaryUnaryMultiCallable[_arcadedb_server_pb2.LookupByRidRequest, _arcadedb_server_pb2.LookupByRidResponse]
    DeleteRecord: _grpc.UnaryUnaryMultiCallable[_arcadedb_server_pb2.DeleteRecordRequest, _arcadedb_server_pb2.DeleteRecordResponse]
    BulkInsert: _grpc.UnaryUnaryMultiCallable[_arcadedb_server_pb2.BulkInsertRequest, _arcadedb_server_pb2.InsertSummary]
    """Insert APIs (unary, client-streaming, and bidi)"""
    InsertStream: _grpc.StreamUnaryMultiCallable[_arcadedb_server_pb2.InsertChunk, _arcadedb_server_pb2.InsertSummary]
    InsertBidirectional: _grpc.StreamStreamMultiCallable[_arcadedb_server_pb2.InsertRequest, _arcadedb_server_pb2.InsertResponse]
    BeginTransaction: _grpc.UnaryUnaryMultiCallable[_arcadedb_server_pb2.BeginTransactionRequest, _arcadedb_server_pb2.BeginTransactionResponse]
    """Transaction operations"""
    CommitTransaction: _grpc.UnaryUnaryMultiCallable[_arcadedb_server_pb2.CommitTransactionRequest, _arcadedb_server_pb2.CommitTransactionResponse]
    RollbackTransaction: _grpc.UnaryUnaryMultiCallable[_arcadedb_server_pb2.RollbackTransactionRequest, _arcadedb_server_pb2.RollbackTransactionResponse]
    GraphBatchLoad: _grpc.StreamUnaryMultiCallable[_arcadedb_server_pb2.GraphBatchChunk, _arcadedb_server_pb2.GraphBatchResult]
    """Graph batch load (client-streaming)"""

@_typing.type_check_only
class ArcadeDbServiceAsyncStub(ArcadeDbServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    StreamQuery: _aio.UnaryStreamMultiCallable[_arcadedb_server_pb2.StreamQueryRequest, _arcadedb_server_pb2.QueryResult]  # type: ignore[assignment]
    """Streaming queries"""
    ExecuteCommand: _aio.UnaryUnaryMultiCallable[_arcadedb_server_pb2.ExecuteCommandRequest, _arcadedb_server_pb2.ExecuteCommandResponse]  # type: ignore[assignment]
    """Execute arbitrary command (INSERT/UPDATE/DDL/etc.)"""
    ExecuteQuery: _aio.UnaryUnaryMultiCallable[_arcadedb_server_pb2.ExecuteQueryRequest, _arcadedb_server_pb2.ExecuteQueryResponse]  # type: ignore[assignment]
    CreateRecord: _aio.UnaryUnaryMultiCallable[_arcadedb_server_pb2.CreateRecordRequest, _arcadedb_server_pb2.CreateRecordResponse]  # type: ignore[assignment]
    """Single-record helpers"""
    UpdateRecord: _aio.UnaryUnaryMultiCallable[_arcadedb_server_pb2.UpdateRecordRequest, _arcadedb_server_pb2.UpdateRecordResponse]  # type: ignore[assignment]
    LookupByRid: _aio.UnaryUnaryMultiCallable[_arcadedb_server_pb2.LookupByRidRequest, _arcadedb_server_pb2.LookupByRidResponse]  # type: ignore[assignment]
    DeleteRecord: _aio.UnaryUnaryMultiCallable[_arcadedb_server_pb2.DeleteRecordRequest, _arcadedb_server_pb2.DeleteRecordResponse]  # type: ignore[assignment]
    BulkInsert: _aio.UnaryUnaryMultiCallable[_arcadedb_server_pb2.BulkInsertRequest, _arcadedb_server_pb2.InsertSummary]  # type: ignore[assignment]
    """Insert APIs (unary, client-streaming, and bidi)"""
    InsertStream: _aio.StreamUnaryMultiCallable[_arcadedb_server_pb2.InsertChunk, _arcadedb_server_pb2.InsertSummary]  # type: ignore[assignment]
    InsertBidirectional: _aio.StreamStreamMultiCallable[_arcadedb_server_pb2.InsertRequest, _arcadedb_server_pb2.InsertResponse]  # type: ignore[assignment]
    BeginTransaction: _aio.UnaryUnaryMultiCallable[_arcadedb_server_pb2.BeginTransactionRequest, _arcadedb_server_pb2.BeginTransactionResponse]  # type: ignore[assignment]
    """Transaction operations"""
    CommitTransaction: _aio.UnaryUnaryMultiCallable[_arcadedb_server_pb2.CommitTransactionRequest, _arcadedb_server_pb2.CommitTransactionResponse]  # type: ignore[assignment]
    RollbackTransaction: _aio.UnaryUnaryMultiCallable[_arcadedb_server_pb2.RollbackTransactionRequest, _arcadedb_server_pb2.RollbackTransactionResponse]  # type: ignore[assignment]
    GraphBatchLoad: _aio.StreamUnaryMultiCallable[_arcadedb_server_pb2.GraphBatchChunk, _arcadedb_server_pb2.GraphBatchResult]  # type: ignore[assignment]
    """Graph batch load (client-streaming)"""

class ArcadeDbServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def StreamQuery(
        self,
        request: _arcadedb_server_pb2.StreamQueryRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_arcadedb_server_pb2.QueryResult], _abc.AsyncIterator[_arcadedb_server_pb2.QueryResult]]:
        """Streaming queries"""

    @_abc_1.abstractmethod
    def ExecuteCommand(
        self,
        request: _arcadedb_server_pb2.ExecuteCommandRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_arcadedb_server_pb2.ExecuteCommandResponse, _abc.Awaitable[_arcadedb_server_pb2.ExecuteCommandResponse]]:
        """Execute arbitrary command (INSERT/UPDATE/DDL/etc.)"""

    @_abc_1.abstractmethod
    def ExecuteQuery(
        self,
        request: _arcadedb_server_pb2.ExecuteQueryRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_arcadedb_server_pb2.ExecuteQueryResponse, _abc.Awaitable[_arcadedb_server_pb2.ExecuteQueryResponse]]: ...

    @_abc_1.abstractmethod
    def CreateRecord(
        self,
        request: _arcadedb_server_pb2.CreateRecordRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_arcadedb_server_pb2.CreateRecordResponse, _abc.Awaitable[_arcadedb_server_pb2.CreateRecordResponse]]:
        """Single-record helpers"""

    @_abc_1.abstractmethod
    def UpdateRecord(
        self,
        request: _arcadedb_server_pb2.UpdateRecordRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_arcadedb_server_pb2.UpdateRecordResponse, _abc.Awaitable[_arcadedb_server_pb2.UpdateRecordResponse]]: ...

    @_abc_1.abstractmethod
    def LookupByRid(
        self,
        request: _arcadedb_server_pb2.LookupByRidRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_arcadedb_server_pb2.LookupByRidResponse, _abc.Awaitable[_arcadedb_server_pb2.LookupByRidResponse]]: ...

    @_abc_1.abstractmethod
    def DeleteRecord(
        self,
        request: _arcadedb_server_pb2.DeleteRecordRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_arcadedb_server_pb2.DeleteRecordResponse, _abc.Awaitable[_arcadedb_server_pb2.DeleteRecordResponse]]: ...

    @_abc_1.abstractmethod
    def BulkInsert(
        self,
        request: _arcadedb_server_pb2.BulkInsertRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_arcadedb_server_pb2.InsertSummary, _abc.Awaitable[_arcadedb_server_pb2.InsertSummary]]:
        """Insert APIs (unary, client-streaming, and bidi)"""

    @_abc_1.abstractmethod
    def InsertStream(
        self,
        request_iterator: _MaybeAsyncIterator[_arcadedb_server_pb2.InsertChunk],
        context: _ServicerContext,
    ) -> _typing.Union[_arcadedb_server_pb2.InsertSummary, _abc.Awaitable[_arcadedb_server_pb2.InsertSummary]]: ...

    @_abc_1.abstractmethod
    def InsertBidirectional(
        self,
        request_iterator: _MaybeAsyncIterator[_arcadedb_server_pb2.InsertRequest],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_arcadedb_server_pb2.InsertResponse], _abc.AsyncIterator[_arcadedb_server_pb2.InsertResponse]]: ...

    @_abc_1.abstractmethod
    def BeginTransaction(
        self,
        request: _arcadedb_server_pb2.BeginTransactionRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_arcadedb_server_pb2.BeginTransactionResponse, _abc.Awaitable[_arcadedb_server_pb2.BeginTransactionResponse]]:
        """Transaction operations"""

    @_abc_1.abstractmethod
    def CommitTransaction(
        self,
        request: _arcadedb_server_pb2.CommitTransactionRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_arcadedb_server_pb2.CommitTransactionResponse, _abc.Awaitable[_arcadedb_server_pb2.CommitTransactionResponse]]: ...

    @_abc_1.abstractmethod
    def RollbackTransaction(
        self,
        request: _arcadedb_server_pb2.RollbackTransactionRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_arcadedb_server_pb2.RollbackTransactionResponse, _abc.Awaitable[_arcadedb_server_pb2.RollbackTransactionResponse]]: ...

    @_abc_1.abstractmethod
    def GraphBatchLoad(
        self,
        request_iterator: _MaybeAsyncIterator[_arcadedb_server_pb2.GraphBatchChunk],
        context: _ServicerContext,
    ) -> _typing.Union[_arcadedb_server_pb2.GraphBatchResult, _abc.Awaitable[_arcadedb_server_pb2.GraphBatchResult]]:
        """Graph batch load (client-streaming)"""

def add_ArcadeDbServiceServicer_to_server(servicer: ArcadeDbServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...

class ArcadeDbAdminServiceStub:
    """-----------------------------------------------------------------------------
    Admin service
    -----------------------------------------------------------------------------
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ArcadeDbAdminServiceAsyncStub: ...
    Ping: _grpc.UnaryUnaryMultiCallable[_arcadedb_server_pb2.PingRequest, _arcadedb_server_pb2.PingResponse]
    GetServerInfo: _grpc.UnaryUnaryMultiCallable[_arcadedb_server_pb2.GetServerInfoRequest, _arcadedb_server_pb2.GetServerInfoResponse]
    ListDatabases: _grpc.UnaryUnaryMultiCallable[_arcadedb_server_pb2.ListDatabasesRequest, _arcadedb_server_pb2.ListDatabasesResponse]
    ExistsDatabase: _grpc.UnaryUnaryMultiCallable[_arcadedb_server_pb2.ExistsDatabaseRequest, _arcadedb_server_pb2.ExistsDatabaseResponse]
    CreateDatabase: _grpc.UnaryUnaryMultiCallable[_arcadedb_server_pb2.CreateDatabaseRequest, _arcadedb_server_pb2.CreateDatabaseResponse]
    DropDatabase: _grpc.UnaryUnaryMultiCallable[_arcadedb_server_pb2.DropDatabaseRequest, _arcadedb_server_pb2.DropDatabaseResponse]
    GetDatabaseInfo: _grpc.UnaryUnaryMultiCallable[_arcadedb_server_pb2.GetDatabaseInfoRequest, _arcadedb_server_pb2.GetDatabaseInfoResponse]
    CreateUser: _grpc.UnaryUnaryMultiCallable[_arcadedb_server_pb2.CreateUserRequest, _arcadedb_server_pb2.CreateUserResponse]
    DeleteUser: _grpc.UnaryUnaryMultiCallable[_arcadedb_server_pb2.DeleteUserRequest, _arcadedb_server_pb2.DeleteUserResponse]

@_typing.type_check_only
class ArcadeDbAdminServiceAsyncStub(ArcadeDbAdminServiceStub):
    """-----------------------------------------------------------------------------
    Admin service
    -----------------------------------------------------------------------------
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    Ping: _aio.UnaryUnaryMultiCallable[_arcadedb_server_pb2.PingRequest, _arcadedb_server_pb2.PingResponse]  # type: ignore[assignment]
    GetServerInfo: _aio.UnaryUnaryMultiCallable[_arcadedb_server_pb2.GetServerInfoRequest, _arcadedb_server_pb2.GetServerInfoResponse]  # type: ignore[assignment]
    ListDatabases: _aio.UnaryUnaryMultiCallable[_arcadedb_server_pb2.ListDatabasesRequest, _arcadedb_server_pb2.ListDatabasesResponse]  # type: ignore[assignment]
    ExistsDatabase: _aio.UnaryUnaryMultiCallable[_arcadedb_server_pb2.ExistsDatabaseRequest, _arcadedb_server_pb2.ExistsDatabaseResponse]  # type: ignore[assignment]
    CreateDatabase: _aio.UnaryUnaryMultiCallable[_arcadedb_server_pb2.CreateDatabaseRequest, _arcadedb_server_pb2.CreateDatabaseResponse]  # type: ignore[assignment]
    DropDatabase: _aio.UnaryUnaryMultiCallable[_arcadedb_server_pb2.DropDatabaseRequest, _arcadedb_server_pb2.DropDatabaseResponse]  # type: ignore[assignment]
    GetDatabaseInfo: _aio.UnaryUnaryMultiCallable[_arcadedb_server_pb2.GetDatabaseInfoRequest, _arcadedb_server_pb2.GetDatabaseInfoResponse]  # type: ignore[assignment]
    CreateUser: _aio.UnaryUnaryMultiCallable[_arcadedb_server_pb2.CreateUserRequest, _arcadedb_server_pb2.CreateUserResponse]  # type: ignore[assignment]
    DeleteUser: _aio.UnaryUnaryMultiCallable[_arcadedb_server_pb2.DeleteUserRequest, _arcadedb_server_pb2.DeleteUserResponse]  # type: ignore[assignment]

class ArcadeDbAdminServiceServicer(metaclass=_abc_1.ABCMeta):
    """-----------------------------------------------------------------------------
    Admin service
    -----------------------------------------------------------------------------
    """

    @_abc_1.abstractmethod
    def Ping(
        self,
        request: _arcadedb_server_pb2.PingRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_arcadedb_server_pb2.PingResponse, _abc.Awaitable[_arcadedb_server_pb2.PingResponse]]: ...

    @_abc_1.abstractmethod
    def GetServerInfo(
        self,
        request: _arcadedb_server_pb2.GetServerInfoRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_arcadedb_server_pb2.GetServerInfoResponse, _abc.Awaitable[_arcadedb_server_pb2.GetServerInfoResponse]]: ...

    @_abc_1.abstractmethod
    def ListDatabases(
        self,
        request: _arcadedb_server_pb2.ListDatabasesRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_arcadedb_server_pb2.ListDatabasesResponse, _abc.Awaitable[_arcadedb_server_pb2.ListDatabasesResponse]]: ...

    @_abc_1.abstractmethod
    def ExistsDatabase(
        self,
        request: _arcadedb_server_pb2.ExistsDatabaseRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_arcadedb_server_pb2.ExistsDatabaseResponse, _abc.Awaitable[_arcadedb_server_pb2.ExistsDatabaseResponse]]: ...

    @_abc_1.abstractmethod
    def CreateDatabase(
        self,
        request: _arcadedb_server_pb2.CreateDatabaseRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_arcadedb_server_pb2.CreateDatabaseResponse, _abc.Awaitable[_arcadedb_server_pb2.CreateDatabaseResponse]]: ...

    @_abc_1.abstractmethod
    def DropDatabase(
        self,
        request: _arcadedb_server_pb2.DropDatabaseRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_arcadedb_server_pb2.DropDatabaseResponse, _abc.Awaitable[_arcadedb_server_pb2.DropDatabaseResponse]]: ...

    @_abc_1.abstractmethod
    def GetDatabaseInfo(
        self,
        request: _arcadedb_server_pb2.GetDatabaseInfoRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_arcadedb_server_pb2.GetDatabaseInfoResponse, _abc.Awaitable[_arcadedb_server_pb2.GetDatabaseInfoResponse]]: ...

    @_abc_1.abstractmethod
    def CreateUser(
        self,
        request: _arcadedb_server_pb2.CreateUserRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_arcadedb_server_pb2.CreateUserResponse, _abc.Awaitable[_arcadedb_server_pb2.CreateUserResponse]]: ...

    @_abc_1.abstractmethod
    def DeleteUser(
        self,
        request: _arcadedb_server_pb2.DeleteUserRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_arcadedb_server_pb2.DeleteUserResponse, _abc.Awaitable[_arcadedb_server_pb2.DeleteUserResponse]]: ...

def add_ArcadeDbAdminServiceServicer_to_server(servicer: ArcadeDbAdminServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
